### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by jukecraft** [SamirTalwar/communitycodeofconduct.com#3]
I'll work on it

**Comment by jukecraft** [comment]
```
<h1>Community Code of Conduct</h1>

<p>All members are required to agree with the following code of conduct. All members of the community are expected to enforce this code at every event, with help from the organisers. We are expecting cooperation from all participants in the community to help ensuring a safe environment for everybody.</p>

<h2>Need Help?</h2>

<p>The contact details of the organisers are on our website and in any emails we have sent.</p>

<h2>The Quick Version</h2>

<p>Our community is dedicated to providing a harassment-free experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion (or lack thereof), or technology choices. We do not tolerate harassment of community members in any form. Sexual language and imagery is not appropriate for any community event, including talks, workshops, parties, Twitter and other online media. Participants violating these rules may be sanctioned or expelled from the event and any future events <em>without a refund</em> (if applicable), or from the community itself, at the discretion of the organisers.</p>

<h2>The Less Quick Version</h2>

<p>Harassment includes offensive verbal comments related to gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion, technology choices, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention.</p>

<p>Participants asked to stop any harassing behavior are expected to comply immediately.</p>

<p>Sponsors are also subject to the anti-harassment policy. In particular, sponsors should not use sexualised images, activities, or other material. Event hosts and attendees, including sponsors, staff and volunteers, should not use sexualised clothing/uniforms/costumes, or otherwise create a sexualised environment.</p>

<p>If a participant engages in harassing behavior, the organisers may take any action they deem appropriate, including warning the offender or expulsion from the event or community with no refund.</p>

<p>If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact an organiser immediately. All of our organisers' contact details are listed on our website.</p>

<p>Organisers will be happy to help participants contact venue security or local law enforcement, provide escorts, or otherwise assist those experiencing harassment to feel safe for the duration of the event. We value your attendance and contributions to the community.</p>

<p>We expect participants to follow these rules at all community events, whether professional, social or a mix of both.</p>

<div class="footer">
    <p><small><em>Original source and credit: <a href="http://2012.jsconf.us/#/about">http://2012.jsconf.us/#/about</a>, <a href="http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy">The Ada Initiative</a> &amp; <a href="http://confcodeofconduct.com/">confcodeofconduct.com</a><br>

Please help by translating or improving: <a href="https://github.com/SamirTalwar/communitycodeofconduct.com">https://github.com/SamirTalwar/communitycodeofconduct.com</a><br>

This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/deed.en_US">Creative Commons Attribution 3.0 Unported License</a></em></small>

</p>
</div>
```

**Comment by jukecraft** [comment]
```
<h1>Verhaltensregeln auf der Konferenz</h1>

<p>Alle Besucher_innen, Redner_innen, Sponsor_innen und Freiwilligen auf dieser Konferenz werden aufgefordert, sich an folgende Verhaltensregeln zu halten. Diese werden vom Personal auf der gesamten Konferenz durchgesetzt. Wir erbitten uns die Mitarbeit aller Anwesenden, um diese Konferenz zu einem sicheren und angenehmen Ort für alle zu machen.</p>

<h2>Brauchst du Hilfe?</h2>

<p>Du hast alle Kontaktmöglichkeiten vorab per Email erhalten.</p>

<h2>Die Kurzfassung</h2>

<p>Wir möchten unseren Teilnehmer_innen eine belästigungsfreie Konferenzerfahrung bieten, unabhängig von Geschlecht, sexueller Orientierung, Behinderung, Aussehen, Körperbau, Ethnizität oder Religionszugehörigkeit (oder Nichtvorhandensein einer solchen). Wir tolerieren keinerlei Belästigung von Konferenzbesucher_innen. Sexualisierte Sprache und Darstellungen sind auf der Konferenz unerwünscht. Dies umfasst den Veranstaltungsort, die Vorträge, Workshops und Feten, sowie Twitter und andere Medien. Teilnehmer_innen, die gegen diese Regeln verstoßen, müssen mit Sanktionen durch das Veranstaltungspersonal rechnen, inklusive eines Verweises der Konferenz <em>ohne Anspruch auf Rückerstattung des Eintrittspreises</em>.</p>

<h2>Die längere Fassung</h2>

<p>„Belästigung“ umfasst unter anderem beleidigende Aussagen über Geschlecht, sexuelle Orientierung, Behinderung, körperliches Aussehen wie Körperbau, Ethnizität oder Religionszugehörigkeit (oder Nichtvorhandensein einer solchen), sexualisierende Darstellungen in öffentlichen Räumen, bewusste Einschüchterung, Stalking, Verfolgung, unerwünschtes Fotografieren oder Aufnehmen, wiederholte Störung von Vorträgen und anderen Veranstaltungen, unerwünschten körperlichen Kontakt und unerwünschte sexuelle Aufmerksamkeit.</p>

<p>Teilnehmer_innen, die wegen solchen Verhaltens ermahnt werden, haben dieses sofort einzustellen.</p>

<p>Diese Verhaltensregeln gelten auch für Sponsor_innen. Insbesondere sollten Sponsor_innen darauf achten, dass sie keine sexualisierenden Bilder, Aktivitäten oder andere sexualisierende Werbemittel einsetzen. Standpersonal (auch Freiwillige) sollten darauf achten, keine sexualisierende Kleidung, Uniformen oder Kostüme zu tragen, oder sonstwie ein sexualisiertes Umfeld zu gestalten.</p>

<p>Sollten Teilnehmer_innen durch belästigendes Verhalten auffallen, steht es dem Konferenzpersonal frei, entsprechende Maßnahmen zu ergreifen, die es für angemessen hält. Dies schließt Ermahnungen bis hin zum Verweis von der Konferenz ein. Im Falle eines Verweises besteht kein Anspruch auf Rückerstattung des Eintrittspreises.</p>

<p>Solltest du dich belästigt fühlen oder mitbekommen, dass jemand anders belästigt wird oder sonstige Probleme auftreten, wende dich bitte sofort an ein Mitglied des Veranstaltungspersonals. Diese sind an ihren entsprechend markierten T-Shirts schnell zu erkennen.</p>

<p>Mitglieder des Konferenzpersonals können euch bei allen Problemen helfen. Dies schließt Kontakt mit dem Security-Personal des Veranstaltungsorts und/oder den Behörden mit ein. Darüber hinaus können wir Begleitungen vermitteln und auch weitere Maßnahmen ergreifen, um Belästigten einen sicheren und angenehmen Besuch der Konferenz zu ermöglichen. Wir schätzen deine Anwesenheit sehr.</p>

<p>Wir erwarten von allen Teilnehmern die Einhaltung dieser Regeln auf der gesamten Konferenz, den Workshops und auf allen weiteren Zusammenkünften im Zusammenhang mit dieser Konferenz.</p>

<div class="footer">
<p><small><em>Original und Quelle: <a href="http://2012.jsconf.us/#/about">http://2012.jsconf.us/#/about</a> &amp; <a href="http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy">The Ada Initiative</a><br>

Bitte helft beim Übersetzen und Verbessern dieser Regeln: <a href="https://github.com/leftlogic/confcodeofconduct.com">http://github.com/leftlogic/confcodeofconduct.com</a><br>

Dieses Werk steht unter der <a rel="license" href="http://creativecommons.org/licenses/by/3.0/deed.de">Creative Commons Namensnennung 3.0 Unported Lizenz</a></em></small>

</p>
</div>
```

**Comment by SamirTalwar** [comment]
Just open a PR with a file named `index-de.html` when you can. :smiley:

**Comment by jukecraft** [comment]
Work in progress

<h1>Verhaltensregeln in der Community</h1>

<p>Alle Mitglieder dieser Community werden aufgefordert, sich an folgende Verhaltensregeln zu halten. Von allen Mitgliedern dieser Community wird erwartet, dass sie diese Regeln bei jeder Veranstaltung durchsetzen, mit der hilfe der Organisierenden. Wir erbitten uns die Mitarbeit aller Teilnehmenden der Community, um einem sicheren und angenehmen Ort für alle zu ermöglichen.</p>

<h2>Brauchst du Hilfe?</h2>

<p>Die Kontaktmöglichkeiten zu den Organisierenden sind auf unserer Webseite und in allen Emails, die wir versenden, zu finden.</p>

<h2>Die Kurzfassung</h2>

<p>Wir möchten allen in unserer Community eine belästigungsfreie Erfahrung bieten, unabhängig von Geschlecht, Geschlechtsidentität oder -ausdruck, Alter, sexueller Orientierung, Behinderung, Aussehen, Körperbau, Ethnizität, Religionszugehörigkeit (oder Nichtvorhandensein einer solchen) oder ihrer bevorzugten Technologien. Wir tolerieren keinerlei Belästigung von Mitgliedern der Community in jedweder Form. Sexualisierte Sprache und Darstellungen sind bei keiner Communityvernstaltung angemessen. Dies umfasst auch Vorträge, Workshops und Parties, sowie Twitter und andere Onlinemedien. Teilnehmende, die gegen diese Regeln verstoßen, müssen mit Sanktionen durch die Organisierenden rechnen. Je nach deren Ermessen kann dieseinen Verweises von der Veranstaltung, jedweder zukunftigen Veranstaltungen <em>ohne Anspruch auf Rückerstattung des Eintrittspreises</em> (falls vorhanden), oder aus der Community selbst beinhalten.</p>

<h2>Die längere Fassung</h2>

<p>„Belästigung“ umfasst unter anderem beleidigende Aussagen über Geschlecht, Geschlechtsidentität oder -ausdruck, Alter, sexueller Orientierung, Behinderung, Aussehen, Körperbau, Ethnizität, Religionszugehörigkeit, bevorzugten Technologien, sexualisierende Darstellungen in öffentlichen Räumen, bewusste Einschüchterung, Stalking, Verfolgung, unerwünschtes Fotografieren oder Aufnehmen, wiederholte Störung von Vorträgen und anderen Veranstaltungen, unerwünschten körperlichen Kontakt und unerwünschte sexuelle Aufmerksamkeit.</p>

<p>Wir erwarten, dass Teilnehmende, die gebeten werden jedwedes belästigende Verhalten zu beenden, dem sofort nachkommen.</p>

<p>Diese Verhaltensregeln gelten auch für Sponsor_innen. Insbesondere sollten Sponsor_innen darauf achten, dass sie keine sexualisierenden Bilder, Aktivitäten oder andere sexualisierende Werbemittel einsetzen. Teilnehmende an Veranstaltungen und Gastgebende, inklusive Sponsor_innen, Standpersonal und Freiwillige sollten keine sexualisierende Kleidung, Uniformen oder Kostüme tragen, oder sonstwie ein sexualisiertes Umfeld gestalten.</p>

<p>Sollten Teilnehmende durch belästigendes Verhalten auffallen, steht es den Organisierenden frei, jede von ihnen als angemessen betrachtete Maßnahmen zu ergreifen. Dies schließt Ermahnungen bis hin zum Verweis von der Veranstaltung oder der Community (ohne Anspruch auf Rückerstattung des Eintrittspreises) ein.</p>

<p>Solltest du dich belästigt fühlen oder mitbekommen, dass jemand anders belästigt wird oder wenn du jedwede andere Bedenken hast, wende dich bitte sofort an eine(n) der Organsierenden. Alle Organisierenden sind auf unserer Webseite aufgelistet.</p>

<p>Organisierende helfen gerne dabei das Security-Personal des Veranstaltungsorts und/oder die Behörden zu kontaktieren. Darüber hinaus können wir Begleitungen vermitteln und auch weitere Maßnahmen ergreifen, um Belästigten einen sicheren und angenehmen Besuch der Konferenz zu ermöglichen. Wir schätzen deine Anwesenheit und deinen Beitrag zur Community.</p>

<p>We expect participants to follow these rules at all community events, whether professional, social or a mix of both.</p>

<p>Wir erwarten von allen Teilnehmenden die Einhaltung dieser Regeln auf allen Veranstaltungen der Community, ob beruflich, gesellig oder gemischt.</p>

<div class="footer">
<p><small><em>Original und Quelle: <a href="http://2012.jsconf.us/#/about">http://2012.jsconf.us/#/about</a> &amp; <a href="http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy">The Ada Initiative</a>&amp; <a href="http://confcodeofconduct.com/">confcodeofconduct.com</a><br>
Bitte helft beim Übersetzen und Verbessern dieser Regeln: <a href="https://github.com/SamirTalwar/communitycodeofconduct.com">https://github.com/SamirTalwar/communitycodeofconduct.com</a><br>
Dieses Werk steht unter der <a rel="license" href="http://creativecommons.org/licenses/by/3.0/deed.de">Creative Commons Namensnennung 3.0 Unported Lizenz</a></em></small>
</p>
</div>
