### ISSUE TITLE
Finnish translation

### ISSUE THREAD

**Issue by tommijoentakanen** [SamirTalwar/communitycodeofconduct.com#5]
Working on Finnish translation with @rinkkasatiainen

**Comment by tommijoentakanen** [comment]
Pull request has been created (https://github.com/tommijoentakanen/communitycodeofconduct.com/pull/1) for:

<h1>Yhteisön toimintaperiaatteet</h1>

<p>Kaikkien yhteisön jäsenien vaaditaan hyväksymään seuraavat toimintaperiaatteet. Kaikkien jäsenten odotetaan orgasiojien avustamana toimeenpanevan nämä käytännöt jokaisessa tapahtumassa. Edellytämme asiassa yhteistyötä kaikilta yhteisön toimintaan osallistuvilta edistääksemme turvallista työympäristöä kaikille.</p>

<h2>Tarvitsetko apua?</h2>

<p>Toimintaperiaatteiden yksityiskohdat löytyvät verkkosivuiltamme ja kaikista lähettämistämme sähköpostiviesteistä.</p>

<h2>Lyhyesti</h2>

<p>Yhteisömme on omistautunut tuottamaan häiriöttömän kokemuksen kaikille riippumatta sukupuolesta, sukupuoli- ilmaistusta tai identiteetistä, iästä, seksuaalisesta suuntautumisesta, invaliditeetista, fyysisestä ulkonäöstä, ruuminrakenteesta, rodusta, etnisyydestä, uskonnosta tai sen puutteesta, tai teknologisista valinnoista. Emme hyväksy yhteisömme jäsenten häirintää missään muodossa. Seksuaalinen kielenkäyttö ja mielikuvat eivät ole sopivia mihinkään yhteisön tapahtumaan, mukaanlukien esitelmät, työpajat, juhlat, Twitter tai muu verkkomedia. Näitä sääntöjä rikkovat osallistujat voidaan tarvittaessa poistaa tapahtumasta, heiltä voidaan myös evätä pääsy tuleviin tapahtumiin (ilman mahdollista maksun palautusta) sekä altistaa sanktioille tai erottaa yhteisöstä.</p>

<h2>Tarkemmin</h2>

<p>Tulossa... (work in progress)</p>

<div class="footer">
    <p><small><em>Original source and credit: <a href="http://2012.jsconf.us/#/about">http://2012.jsconf.us/#/about</a>, <a href="http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy">The Ada Initiative</a> &amp; <a href="http://confcodeofconduct.com/">confcodeofconduct.com</a><br>
Please help by translating or improving: <a href="https://github.com/SamirTalwar/communitycodeofconduct.com">https://github.com/SamirTalwar/communitycodeofconduct.com</a><br>
This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/deed.en_US">Creative Commons Attribution 3.0 Unported License</a></em></small>
</p>
</div>

**Comment by jukecraft** [comment]
Sorry @SamirTalwar, missed the fact this issue was open. Can be closed, too

**Comment by SamirTalwar** [comment]
Don't apologise for that. I think it's my job. 😉
